language:
  python

cache: pip

python:
  - "3.6"

before_script:
  - pip install flake8 isort

script:
  - flake8 benchmarks
  - isort --check-only --recursive benchmarks
  - python3 -m benchmarks.tests

before_deploy:
  - mkdir -p html
  - python3 -u -m benchmarks --display_format=html $EMAILS_ZIP_URL | tee html/index.html

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: html
  on:
    branch: master
